### ISSUE TITLE
Check if the photo is still available at execution

### ISSUE THREAD

**Issue by CynaCons** [ssimunic/Daily-Reddit-Wallpaper#16]
Once, a photo hosted on Imgur made it's way to the top of the subreddit. However when I ran the script, the photo was no longer available on Imgur. As a result my desktop background was a big 'not available' or something.

Do you think there is a way to prevent that ?

**Comment by ssimunic** [comment]
Yes, it has been fixed already with [this commit](https://github.com/ssimunic/Daily-Reddit-Wallpaper/commit/56996ce0044a70495e4b2541433579c24153fc3f)

It was the top image of /r/wallpapers yesterday.

**Comment by remggo** [comment]
This would not fix the problem if a picture is beeing taken down from OP, or has the 'This image is not available' always 'gallery' in its URL?

**Comment by ssimunic** [comment]
@remggo , the issue happened because it was downloading non existing image using gallery ID, which is not valid image URL.
But yes, you are correct, if there is valid imgur link which was removed, then it would download non existing image. That is not the case usually, as mods delete the post if this happens, but option to integrate imgur api should be considered.

**Comment by ssimunic** [comment]
Fixed with 5deb482d57b3d922edf289b61bdf5d6a97d56401
